language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=test/native/test_first.cpp
install:
    - pip install -U platformio
script:
    - pio test -e native

